; PlatformIO Project Configuration
; ESP8266 - SoftAP UDP Receiver for Joint Telemetry

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
    -D WIFI_SSID=\"RobotVR_AP\"
    -D WIFI_PASS=\"12345678\"
    -D UDP_PORT=5000
    -D NUM_JOINTS=6
